dist: xenial
language: node_js

node_js:
  - "12"
  - "14"

install:
  - yarn

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  npm: true
  yarn: true
  directories:
    - node_modules

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "12"

script:
  - yarn build
  - yarn test
